"""Adding maps url

Revision ID: 0554dc887ffa
Revises: 7078ed0a27a1
Create Date: 2023-06-26 21:05:50.486007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0554dc887ffa'
down_revision = '7078ed0a27a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maps_url', sa.String(), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('phone', 'restaurants', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('maps_url')

    # ### end Alembic commands ###
