"""Initial Migration

Revision ID: 7078ed0a27a1
Revises: 
Create Date: 2023-06-26 11:27:55.458981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7078ed0a27a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=False))
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
        batch_op.alter_column('menu',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('british')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('turkish')
        batch_op.drop_column('indian')
        batch_op.drop_column('caribbean')
        batch_op.drop_column('italian')
        batch_op.drop_column('address_1')
        batch_op.drop_column('chinese')
        batch_op.drop_column('vegetarian')
        batch_op.drop_column('state')
        batch_op.drop_column('mexican')
        batch_op.drop_column('thai')
        batch_op.drop_column('brunch')
        batch_op.drop_column('chicken')
        batch_op.drop_column('country')
        batch_op.drop_column('asian')
        batch_op.drop_column('seafood')
        batch_op.drop_column('bbq')
        batch_op.drop_column('vegan')
        batch_op.drop_column('address_2')
        batch_op.drop_column('halal')
        batch_op.drop_column('african')
        batch_op.drop_column('japanese')
        batch_op.drop_column('korean')
        batch_op.drop_column('burger')
        batch_op.drop_column('american')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('american', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('burger', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('korean', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('japanese', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('african', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('halal', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('address_2', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('vegan', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('bbq', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('seafood', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('asian', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('chicken', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('brunch', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('thai', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('mexican', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('vegetarian', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('chinese', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('address_1', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('italian', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('caribbean', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('indian', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('turkish', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('zipcode', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('british', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('menu',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
        batch_op.drop_column('address')

    # ### end Alembic commands ###
